### ISSUE TITLE
Problems entering moth data in Spain

### ISSUE THREAD

**Issue by chrisvanswaay** [BiologicalRecordsCentre/ABLE#478] opened 2022-09-25 11:02 UTC
@JimBacon @kazlauskis @DavidRoy 
Hi all, got this email from Constanti in Spain (canliro@gmail.com). I will send him the link to this discussion. I think this issue is in the webversion trying to enter moth counts. Can you have a look?
Chris

------
Now that the CBMS seasons has finished, I started to enter my moth trap data, using the app provided by eBMS. However, I got stuck in my first trial, even if I tried many times.

The problem is that, once I tried to submit the data, there appears a message stating that the spatial reference must be supplied (for the selected trap). However, my colleague Jordi Corbera has exactly the same format for the location of their traps, and it works (??).

See below my moth trap details (for trap 1), with lat/long coordinates. I put directly lat/long coordinates as the map gives too few details to locate the traps using the map instead. See, however, that the situation of the trap is correctly given on the map once giving the coordinates, which makes the message of 'spatial reference must be supplied' very strange.

Unfortunately, the list of species and photos, etc. cannot be saved after the message of spatial reference, so all the work is wasted. 

Please, give me what the hell does not work with my trap/list. So far, I cannot proceed to upload the data...

Cheers,

Constanti
![thumbnail_image](https://user-images.githubusercontent.com/25886005/192140241-f87f57ef-8e33-433c-9017-9046d6296c76.png)

**Comment by canliro** [comment] 2022-09-25 13:53
Hi Jim, hi David,
The problem seems to be related with the coordinates given to the trap. I used lat/long, as you can see in the screen capture. The odd thing is that, after several trials with the same message ('spatial reference must be supplied'), I asked my colleague Jordi Corbera, who has been uploading data from his trap samples without problems, the format of coordinates that he uses. I then used the same format and saved it for trap 1... but it still had the same message once I tried to submit the data.

**Comment by JimBacon** [comment] 2022-09-26 12:00
Hi @canliro 

I am sorry you were having problems with the website.
I think I know the cause, which I have now fixed.
Please try again and let us know if it is okay.

For information, this is what I found:
If you chose the trap and then the date on the calendar, as below, the location information was not set correctly.
![image](https://user-images.githubusercontent.com/2545390/192269428-0517cde7-a385-474e-9301-157514b424f1.png)

If you chose the location after the date, as below, then it worked.

![image](https://user-images.githubusercontent.com/2545390/192269237-cda1985b-a635-48f5-ae74-bf158e95dd27.png)

**Comment by canliro** [comment] 2022-09-27 21:56
Dear Jim,

I confirm that the problem is solved and that I've started to successfully
enter my moth data.

Thanks for your help and the quick reaction!

All the best,

Constanti



Missatge de JimBacon ***@***.***> del dia dl., 26 de set.
2022 a les 14:00:

**Closed** 2022-09-28 07:57 UTC
Labels: urgent
