### ISSUE TITLE
Wrong Time of sighting

### ISSUE THREAD

**Issue by JurrienVanDeijk** [BiologicalRecordsCentre/ABLE#638] opened 2023-10-18 14:39 UTC
When I download an export (Download 15 min single species occurances zipped scs) from the 15 minute single species timed-count downloads then the time of the observation is 2 hours behind. The start and end time is correct. See also the printscreen from Excel below:

![image](https://github.com/BiologicalRecordsCentre/ABLE/assets/96239244/d58e706f-ee11-4098-ac26-757d516c573d)
.

**Comment by JimBacon** [comment] 2023-10-18 14:43
Duplicate of https://github.com/BiologicalRecordsCentre/ABLE/issues/606

**Closed as completed by JimBacon** 2023-10-18 14:43 UTC
