### ISSUE TITLE
Section duplication in Data Entry Page - eBMS website

### ISSUE THREAD

**Issue by CrisSevilleja** [BiologicalRecordsCentre/ABLE#317] opened 2020-12-02 08:21 UTC
Transects Pineta and Soaso from Spain have section 1 duplicated when entering data in the Data Entry Page. 
Please can you resolve this issue? thanks

@DavidRoy @Gary-van-Breda @johnvanbreda 

<img width="454" alt="Fernando Jubete_Soaso section duplication" src="https://user-images.githubusercontent.com/25052478/100847190-c5442300-347f-11eb-99e8-cdca7b616c96.PNG">
<img width="423" alt="Fernando Jubete_Pineta section duplication" src="https://user-images.githubusercontent.com/25052478/100847192-c5dcb980-347f-11eb-9b2e-244338fa0a01.PNG">

**Comment by CrisSevilleja** [comment] 2021-04-26 13:52
Another transect has a duplicated section, the ID=257172 | **PARQUE NATURAL DE LA MATA** | 38.02113N 0.66615W, shows section 2 duplicated when registering new visits. I included the data in the first section of S2 to remove the second S2. 

@DavidRoy

**Comment by CrisSevilleja** [comment] 2021-12-13 16:06
These duplications are still on the transects. Is this related to issue #269 ?

**Comment by DavidRoy** [comment] 2021-12-13 16:34
@Gary-van-Breda are you able to pick this up?

**Comment by Gary-van-Breda** [comment] 2021-12-14 09:00
Yes...

**Comment by CrisSevilleja** [comment] 2022-07-05 16:26
@JimBacon and @Gary-van-Breda another transect with a duplicated section:

ID= 255860 | ICNF PNAL Arnal (EBMS:Portugal:70) shows section 8 duplicated and even it is not possible to enter data on this section at all (as the user reported, I didn't try). 

If it is not possible to remove the duplicated section, please at least,  could it be possible to allow including data on this duplicated section? It has to be frustrating for the user not completing the survey. 

I can understand it is difficult to sort out this problem on the current transects, but it would be important to solve this duplication to avoid happening in new transects created. 
Thank you

**Comment by JimBacon** [comment] 2022-07-12 10:01
I am going to start fixing these in the database. The duplicate sections in ID= 255860 | ICNF PNAL Arnal (EBMS:Portugal:70) were created on 9th March 2021 so it doesn't signal a fault with the current transect editing code.

@kazlauskis, does the app keep a local copy of the transect sections and will we need to arrange an update if I change them on the warehouse?

**Comment by JimBacon** [comment] 2022-07-13 08:53
For info, I've looked at every pair of duplicates and made a decision about which I am going to keep and which to delete. Initially I thought I would be keeping the higher ID, but no. Then I thought the most recently updated - not quite. Also a couple of odd ones noted below.

Next step is to reassign samples from sections being deleted to sections being kept, checking for, and trying to remove, duplication if the same occurrences were added to both sections.

| Parent ID | Section Name                      | Keep ID | Delete ID |
|-----------|-----------------------------------|---------|-----------|
| 223827    | PINETA - S1                       | 226354  | 223890    |
| 223829    | SOASO - S1                        | 226361  | 223892    |
| 243575    | Grevenmacher Gruussfooscht - S1   | 245052  | 245051    |
| 243575    | Grevenmacher Gruussfooscht - S10  | 243624  | 243584    |
| 243575    | Grevenmacher Gruussfooscht - S14  | 244313  | 243586    |
| 243575    | Grevenmacher Gruussfooscht - S3   | 243595  | 243593    |
| 243575    | Grevenmacher Gruussfooscht - S6   | 243623  | 243580    |
| 244357    | Castelleone - S5                  | 244390  | 244362    |
| 244357    | Castelleone - S6                  | 244389  | 244363    |
| 252427    | Battaglietta - S2                 | 252434  | 252429    |
| 252427    | Battaglietta - S3                 | 252433  | 252430    |
| 253940    | Qormi - Wied Qirda - S4           | 253950  | 253949    |
| 255860    | ICNF PNAL Arnal - S8              | 255868  | 255867    |
| 257172    | PARQUE NATURAL DE LA MATA - S2    | 257177  | 257174    |
| 257639    | Hajnowski tryb - S1               | 257643  | 257642    |
| 260636    | 087_070 Waldbredimus_BB - S2      | 260654  | 260656    |
| 260636    | 087_070 Waldbredimus_BB - S3      | 260653  | 260655    |
| 261110    | Fossa della Garofala - S1         | 261128  | 261111    |
| 261110    | Fossa della Garofala - S6         | (1)       |          |
| 262685    | San Donà di Piave (Grassaga) - S1 | 262686  | 262688 (2)   |
| 267137    | Capo Rama - S2                    | 267139  | 267141 (3)   |
| 279467    | Bademağacı Village - S1           | 279468  | 279471    |
| 279538    | Bernate Ticino MI - IOLAS 02 - S2 | 279639  | 279637    |
| 282143    | Nemunaitis, Pakrantė II - S2      | 282671  | 282256    |
| 282143    | Nemunaitis, Pakrantė II - S9      | 282676  | 282661    |
| 282885    | Himberg Schadeteich - S4          | 282895  | 282890    |
| 285410    | Budapest_3_Mocsárosdűlő - S4      | 285504  | 285502    |
| 285410    | Budapest_3_Mocsárosdűlő - S5      | 285659  | 285661    |
| 285994    | test3 - S1                        | 286009  | 285995    |
| 285994    | test3 - S15                       | 286004  | 286003    |
| 285994    | test3 - S2                        | 286010  | 286006    |
| 285994    | test3 - S3                        | 286008  | 286005    |
| 285994    | test3 - S4                        | 286007  | 285996    |
| 291834    | Buchberg, Lesesteinriegel - S4    | 291848  | 291846    |
| 292527    | Kaunas - S3                       | 292530  | 292529 (4)  |
| 292628    | Cascata - S1                      | 292629  | 292956    |

(1) All sections except 1 (location IDs 261112, 261113, 261114, 261127 & 261129) were deleted as they had no boundary_geom and no associated samples.
(2) Section 3 (location ID 262687) was deleted as it had no boundary_geom, no samples, and there was no section 2.
(3) Section 4 (location ID 267140) was deleted as it had no boundary_geom, no samples, and there was no section 3.
(4) Section 2 (location ID 292532) was updated with the boundary_geom of S3 (location ID 292529)

**Comment by JimBacon** [comment] 2022-07-14 14:01
For info, the following matrices explain my strategy for reassigning samples of sections to keep and delete

<table>
    <tr>
        <th colspan=2 rowspan=2>Transect</th>
        <th colspan=2>Sample of section to delete</th>
    </tr>
    <tr>
        <th>absent</th>
        <th>present</th>
    </tr>
    <tr>
        <th rowspan=2>Sample of section to keep</th>
        <th>absent</th>
        <td>No action</td>
        <td>Change location_id so sample refers to section being kept.</td>
    </tr>
    <tr>
        <th>present</th>
        <td>No action</td>
        <td>Depends on occurrences</td>
    </tr>
</table>

Where a transect has samples for both the section-to-keep and the section-to-remove then the action depends on whether there are occurrences attached to the sample.

<table>
    <tr>
        <th colspan=2 rowspan=2>Both sections present</th>
        <th colspan=2>Occurrences on section to delete</th>
    </tr>
    <tr>
        <th>none</th>
        <th>some</th>
    </tr>
    <tr>
        <th rowspan=2>Occurrences on section to keep</th>
        <th>none</th>
        <td>Delete sample of section to delete</td>
        <td>Change location_id so sample with occurrences refers to section being kept. Delete sample without occurrences.
</td>
    </tr>
    <tr>
        <th>some</th>
        <td>Delete sample of section to delete</td>
        <td>Happily, I think there are no instances of this case.</td>
    </tr>
</table>

Unfortunately, while probing the data to evaluate this strategy, an additional problem has been detected. There are transects (parent samples) having multiple section records (samples) for the same section (location). This should not arise and, before proceeding with the above plan we have to remove this duplication.

**Comment by JimBacon** [comment] 2022-07-14 15:17
It appears that the duplicate samples have arisen when records have been created but one is updated to hold the occurrences and attributes while the other can be discarded. For example, the walk with sample id 11913614 has two records for the section with location id 244390. They have the following properties

<table>
    <tr>
        <th>sample_id</th>
        <td>11913628</td>
        <td>11913621</td>
    </tr>
    <tr>
        <th>created_on</th>
        <td>2020-09-26 22:04:14</td>
        <td>2020-09-26 22:04:13</td>
    </tr>
    <tr>
        <th>updated_on</th>
        <td>2020-09-26 22:04:14</td>
        <td>2020-09-26 22:04:24</td>
    </tr>
    <tr>
        <th>count of occurrences</th>
        <td>0</td>
        <td>2</td>
    </tr>
    <tr>
        <th>sample attributes</th>
        <td>{"1387":"80"}</td>
        <td>{"1387":"80","1457":"20"}</td>
    </tr>
</table>

This pattern is consistent across all the duplicates in our realm of interest so we can simply delete the older ones and their associated attribute values. This was done with the following query
```
WITH ebms_sections AS (
	SELECT l.* 
	FROM locations l
	JOIN locations_websites lw
		ON lw.location_id = l.id
		AND lw.website_id = 118
	WHERE l.deleted = false
		AND l.location_type_id = 778
),
duplicate_sections AS (
	SELECT l1.* 
	FROM ebms_sections l1
	JOIN ebms_sections l2
		ON l2.name = l1.name
		AND l1.parent_id = l2.parent_id
	WHERE l2.id != l1.id
	ORDER BY l1.parent_id, l1.code, l1.id
),
walks_with_multiple_samples_per_section AS (
	SELECT s.parent_id, s.location_id, count(s.id)
	FROM samples s
	JOIN duplicate_sections ds
		ON ds.id = s.location_id
	WHERE s.survey_id = 562
	GROUP BY s.parent_id, s.location_id
	HAVING count(s.id) > 1
	ORDER BY parent_id, location_id
),
samples_to_delete AS (
	SELECT DISTINCT ON (s.parent_id, s.location_id)
		s.parent_id, s.id, s.location_id, s.updated_on,
		(SELECT count(*) 
			FROM occurrences 
			WHERE sample_id = s.id
		) count_occ,
		snf.attrs_json
	FROM samples s
	JOIN walks_with_multiple_samples_per_section w
		ON w.parent_id = s.parent_id
		AND w.location_id = s.location_id
	JOIN cache_samples_nonfunctional snf
		ON snf.id = s.id
	ORDER BY s.location_id, s.parent_id, updated_on ASC
)
UPDATE samples s
SET deleted = true, updated_on = now(), updated_by_id = 2
FROM samples_to_delete std
WHERE s.id = std.id
```
and
```
UPDATE sample_attribute_values sav
SET deleted = true, updated_on = now(), updated_by_id = 2
FROM samples_to_delete std
WHERE sav.sample_id = std.id
```

**Comment by JimBacon** [comment] 2022-07-18 15:24
The following updates were performed to relocate samples according to the strategy and then delete the duplicate locations

1. Where a walk has a sample from a section to delete and there is no sample from the corresponding section to keep.
```
update samples s
set 
	location_id = dups.id_to_keep,
	updated_on = now(),
	updated_by_id = 2
from 
	samples_to_relocate str,
	duplicate_pairs dups
where s.id = str.id
	and dups.pair_id = str.pair_id
```
2. Where a walk has samples from both a section to delete and the corresponding section to keep but there are no occurrences on the sample of the section to delete. 
```
update samples s
set 
	deleted = true,
	updated_on = now(),
	updated_by_id = 2
from 
	samples_to_delete std
where s.id = std.id
```
3. Where a walk has samples from both a section to delete and the corresponding section to keep but there are no occurrences on the sample of the section to keep. 
```
update samples s
set
	location_id = dups.id_to_keep,
	updated_on = now(),
	updated_by_id = 2
from 
	samples_with_occ_to_relocate str,
	duplicate_pairs dups
where s.id = str.id
	and dups.pair_id = str.pair_id;
```
Having performed this update it was necessary to rework the query to obtain `samples_without_occ_to_delete` as 
```
select d.pair_id, d.id
from samples_of_location_to_keep d
join samples_of_location_to_keep k
	on k.parent_id = d.parent_id
	and k.pair_id = d.pair_id
	and k.id != d.id
where d.count_occ = 0 and k.count_occ > 0
```
These records were then deleted by 
```
update samples s
set
	deleted = true,
	updated_on = now(),
	updated_by_id = 2
from 
	samples_without_occ_to_delete std
where s.id = std.id
```
4. Finally, having reassigned samples so that none refer to the locations we wish to delete, we can finally delete those locations as follows.
```
update locations l
set 
	deleted = true,
	updated_on = now(),
	updated_by_id = 2
from 
	duplicate_pairs dups
where dups.id_to_delete = l.id
```

**Comment by JimBacon** [comment] 2022-07-18 15:31
@CrisSevilleja I think I have repaired the database so there are currently no duplicate transect sections. Could you check it looks okay and see if solves the problems for the recorders?

**Comment by kazlauskis** [comment] 2022-07-19 11:20
> @kazlauskis, does the app keep a local copy of the transect sections and will we need to arrange an update if I change them on the warehouse?

@JimBacon The app caches the section locations, but the user can manually refresh the list. I remember you said uploading a sample with a deleted location id won't result in an error. If some locations were deleted, I should probably refresh the locations automatically in the background for the user in the app then.

**Comment by CrisSevilleja** [comment] 2022-07-25 13:41
@JimBacon such incredible work. Thank you so much for taking the time and patience to check every possible situation, solve the duplicated samples and leave the transects without duplicated sections. The most important part is the data is saved despite these duplications. 

I did the first checks on the transects I knew they had duplicated sections and they appear correctly when entering the data! :D I have already written to the coordinators to check those transects, so I hope no problems are reported. 

Again thank you so much for working hard on this and solving it. I hope now no more transects are generated with duplicated sections. For me, this issue can be closed. 
Cheers

**Comment by JimBacon** [comment] 2022-09-05 14:49
I've just checked and there is a new transect with duplicate sections: https://butterfly-monitoring.net/ebms-site-details?id=297750 has two S2 sections.

I guess this indicates that there is still a bug in the transect creation code.

**Comment by DavidRoy** [comment] 2022-09-05 14:53
@Gary-van-Breda is this a problem with the site setup form

**Comment by DavidRoy** [comment] 2022-12-01 13:17
@JimBacon are you able to resolve this without Gary's input?

**Comment by JimBacon** [comment] 2022-12-01 15:06
I can certainly investigate and try to recreate the problem as a first step.

**Comment by JimBacon** [comment] 2023-01-30 17:10
Just picking this up. There are now 9 duplicate section-pairs. The most recent was created on 4th Jan, 2023 indicating the cause  of this problem is still present.

Transect ID | Section Name | ID 1 | ID 2
---|---|---|---
297750 | Jamestown - S2 | 297752 | 297753
300311 | Transecto Universidad - S1 | 300312 | 300493
300311 |Transecto Universidad - S3 | 300314 | 300492
301062 | VALLE PERDIDO - S1 | 301063 | 301068
301726 | TAMAJON - S3 | 301729 | 301732
301726 | TAMAJON - S4 | 301730 | 301731
303583 | EL BERRUECO - S5 | 304571 | 304572
304367 | Gaudella - S1 | 304368 | 304369
304367 | Gaudella - S2 | 304370 | 304371

**Comment by JimBacon** [comment] 2023-02-01 17:32
I have been able to recreate the duplicate sections and also produce a variety of other invalid combinations of sections. This is possible because of two problems:

1. The 'insert section' command can be triggered multiple times simultaneously
2. The 'insert section' command can be triggered while the 'remove section' command is in progress.

The problem is compounded by the fact that the transect editor does not show the duplicate sections although they exist and subsequently appear on the recording form.

It is easy to fall in to the trap of multiple inserts because the website responds very slowly and there is no indication (except a plea to wait which can be dismissed) that it is actually doing anything.

I will investigate some changes to the user interface to prevent this from happening.

**Comment by CrisSevilleja** [comment] 2023-02-02 09:21
Indeed, it makes sense this problem is coming from the slow reply from the website. Thanks for getting deep on this, let´s hope it can be solved.

**Comment by JimBacon** [comment] 2023-02-14 16:49
I have deployed some changes to the user interface (https://github.com/Indicia-Team/client_helpers/commit/8db8f6b8a62096cf61e115170736735e62ef4091) which should prevent the user from creating duplicate sections.

I still need to clean up the database to remove the duplicate sections which have been created.

**Comment by JimBacon** [comment] 2023-02-15 16:57
I've looked at all the duplicate sections and made decisions about which to keep and which to delete as follows. There were no samples recorded yet against any of the transects so the deletions were performed via the warehouse website.

Parent ID | Section Name | Keep ID | Delete ID
---|---|---|---
297750 | Jamestown - S2 | 297752 | 297753
300311 | Transecto Universidad - S1 | 300493 | 300312
300311 | Transecto Universidad - S3 | 300492 | 300314
301062 | VALLE PERDIDO - S1 | 301063 | 301068, 301064(S5), 301065(S6) (note 1)
301726 | TAMAJON - S3 | 301732 | 301729
301726 | TAMAJON - S4 | 301731 | 301730
303583 | EL BERRUECO - S5 | 304572 | 304571, 304570(S6), 304586(S8) (note 2)
304367 | Gaudella - S1 | 304369 | 304368
304367 | Gaudella - S2 | 304371 | 304370 (note 3)
306524 | Roccelletta - S1 | 306534 | 306526
306524 | Roccelletta - S5 |  | 306529, 306532 (note 4)

Notes
1.  There was no S4 and No. of Sections was 3. S5 and S6 had no boundary_geom.
2.  There was no S7 and No. of Sections was 5. S6 and S8 had no boundary geom.
3.  No. of Sections changed from 1 to 2 and Overall Length from 2436 to 2387 
4. There were 3 of S5. No. of Sections changed from 4 to 5.

**Comment by JimBacon** [comment] 2023-02-15 17:47
Seems to be a problem in Chrome when javascript tries to refresh the page after insert or delete so that you get stuck waiting forever. Possibly due to # in url.

**Comment by JimBacon** [comment] 2023-02-16 11:04
Page refresh issue fixed by https://github.com/Indicia-Team/client_helpers/commit/8c8a1cc154c8d977d3530d9c32a4074b10ac48d8

**Closed by JimBacon** 2023-02-16 11:04 UTC
Labels: urgent
