### ISSUE TITLE
Annual report - Sample - Missing temperature field

### ISSUE THREAD

**Issue by xaviermestdagh** [BiologicalRecordsCentre/ABLE#494] opened 2022-11-08 10:58 UTC
Hi,
In the Samples and Occurrences exports form the [Annual report](https://butterfly-monitoring.net/annual-report) is missing the two Temperature related fields
![image](https://user-images.githubusercontent.com/24294138/200546973-f918ce82-1309-4a89-b136-3e303ed7755a.png)
Those fields disapeared because present in the past.

**Comment by CrisSevilleja** [comment] 2022-11-18 10:53
One user reported to me the same, Temperature fields are not included on the downloaded file from the Annual report. He uses the app to include the data of the transects and he knows he included the temperature in the visits but he is not able to see it on the website either on the download file. It looks like a missing connection between the app and the website @kazlauskis , although the missing fields on the download files is another thing. Two different problems?

![thumbnail_93b0e95c-fdea-4bf4-bf87-832a0905c397](https://user-images.githubusercontent.com/25052478/202688303-1dd38f4a-0738-44e7-afb7-f68ba53201fa.jpg)
<img width="640" alt="thumbnail_Captura de pantalla 2022-11-08 a las 9 10 55" src="https://user-images.githubusercontent.com/25052478/202688276-7bf5917e-9848-4569-917a-044a625d9055.png">

**Comment by CrisSevilleja** [comment] 2022-11-18 11:05
Checking on My downloads page, the samples download file has the field Temp (Deg C) but for the last visits (since Jun-July) don't show the temperature when I checked they are registered on the website. 
[download-637765d94ac570.74437862.csv](https://github.com/BiologicalRecordsCentre/ABLE/files/10040681/download-637765d94ac570.74437862.csv)

**Comment by kazlauskis** [comment] 2022-11-18 11:37
@CrisSevilleja the app is uploading the weather information but these values are not mandatory so not all of the records will have this info. If you know any record that has some of the values on the app but not on the website, then please share the record ID and app screenshots and I'll have a look.

**Comment by CrisSevilleja** [comment] 2022-11-18 12:33
@kazlauskis I am talking about transect records where the Temperature is a mandatory field to complete the survey on the app. The app screenshot is above and the Sample ID is 18560392 for the transect on 30/05/2022 transect Añisclo EBMS:Spain:80

**Comment by kazlauskis** [comment] 2022-11-18 13:41
I've checked this up and can't find how to reproduce this issue yet. It would be useful if Fernando tried to update the app to the latest v1.18.1 and uploaded a training transect record. The training records can be enabled on the app settings page by switching the 'Training Mode' on.

**Comment by JimBacon** [comment] 2022-11-20 10:15
To my surprise, I think this is one issue!

It looks as if the configuration of the survey has been changed by someone so that the attribute used for storing temperature now has ID 1660 compared to 1388 at some point in the past.

The annual report download is trying to include a column with ID 1388 (which is then probably omitted as it is no longer associated with the survey) and the sample record 18560392 has a value for attribute 1388.

We need to know which is correct. They have slightly different temperature ranges.
 * 1388: 4 to 39 and 40+
 * 1660: -0, 0 to 40 and 40+
@DavidRoy, can you shed any light on the answer?
@kazlauskis, which temperature attribute does the current version of the app use?

Then we need to ensure the app and the website are both using the correct value (and corresponding terms). Finally, I will probably need to go through the records and clean up. I count ~3k transect records using attribute 1660 and ~14k records using 1388.

**Comment by kazlauskis** [comment] 2022-11-21 07:32
@JimBacon In the v1.17.0 app update (6 months ago) we have expanded the temperature ranges https://github.com/BiologicalRecordsCentre/ABLE/issues/397. Other surveys also used the old `smpAttr:1388` so we have created the `smpAttr:1660` with the new temperature range. The downloads should return the new attribute. I understand this requires updating the reports now. Is there any better way to change survey attributes in the future?

**Comment by JimBacon** [comment] 2022-11-23 17:35
This is work in progress. So far I've made changes to the follow pages

- https://brc-ebms.lndo.site/annual-report
- https://butterfly-monitoring.net/mydata/downloads
- https://brc-ebms.lndo.site/downloads

These will now list temperatures for recent records made with `smpAttr:1660` and omit temperatures for older records made with `smpAttr:1388`. Once I have updated the database to migrate the 1388 attributes to 1660 then they will list all records.

Still 20 more forms to check for use of the attribute and alter if necessary.

**Comment by JimBacon** [comment] 2022-11-28 17:07
I have also updated the following forms (some of which may not actually be used):

- https://butterfly-monitoring.net/index.php/mydata/samples/edit
- https://butterfly-monitoring.net/index.php/elastic/my-records
- https://butterfly-monitoring.net/index.php/enter-app-timed-count
- https://butterfly-monitoring.net/index.php/enter-app-record
- https://butterfly-monitoring.net/index.php/download-indicia

The following forms were not changed and still refer to sample attribute 1388 because survey ID 563 (EBMS Other timed counts) has not been altered to use 1660. I wonder if they are no longer used.

- https://butterfly-monitoring.net/index.php/input-timed-count
- https://butterfly-monitoring.net/index.php/my-timed-counts
- https://butterfly-monitoring.net/index.php/all-timed-counts

**Comment by JimBacon** [comment] 2022-11-28 17:42
In preparation for migrating existing records from sample attribute 1388 to 1660 I note the following changes in the term list IDs (stored in the sample attribute values table) will be needed.

Term | Old ID | New ID
------|--------|--------
4 | 17774 | 20128
5 | 17775 | 20129
6 |  17776 | 20130
7 | 17777 | 20131
8 | 17778 | 20132
9 | 17779 | 20133
10 | 16530 | 20134
11 | 16531 | 20135
12 | 16532 | 20136
13 | 16533 | 20137
14 | 16534 | 20138
15 | 16535 | 20139
16 | 16536 | 20140
17 | 16537 | 20141
18 | 16538 | 20142
19 | 16539 | 20143
20 | 16540 | 20144
21 | 16541 | 20145
22 | 16542 | 20146
23 | 16543 | 20147
24 | 16544 | 20148
25 | 16545 | 20149
26 | 16546 | 20150
27 | 16547 | 20151
28 | 16548 | 20152
29 | 16549 | 20153
30 | 16550 | 20154
31 | 16551 | 20155
32 | 16552 | 20156
33 | 16553 | 20157
34 | 16554 | 20158
35 | 16555 | 20159
36 | 17759 | 20160
37 | 17760 | 20161
38 | 17761 | 20162
39 | 17762 | 20163
40+ | 18878 | 20164
Not recorded / no data | 16556 | 20167

I note that, in the old list, 40+ meant 'greater than or equal to 40' whereas, in the new list, it means 'greater than 40'.  There is only one sample that this affects.

**Comment by JimBacon** [comment] 2022-11-29 17:12
This query was executed to update the` sample_attribute_values` table
```
UPDATE sample_attribute_values sav
SET 
	sample_attribute_id = 1660,
	int_value = CASE
		-- 10 to 35
		WHEN sav.int_value <= 16555 THEN sav.int_value + 3604
		-- Not recorded
		WHEN sav.int_value = 16556 THEN 20167
		-- 36 to 39
		WHEN sav.int_value <= 17762 THEN sav.int_value + 2401
		-- 4 to 9
		WHEN sav.int_value <= 17779 THEN sav.int_value + 2354
		-- 40+
		WHEN sav.int_value =18878 THEN 20164-- 36 to 39
		WHEN sav.int_value <= 17762 THEN sav.int_value + 2401
		-- 4 to 9
		WHEN sav.int_value <= 17779 THEN sav.int_value + 2354
		-- 40+
		WHEN sav.int_value =18878 THEN 20164
	END,
	updated_on = now(),
	updated_by_id =2
FROM samples s
WHERE 
	s.id = sav.sample_id AND
	sav.sample_attribute_id = 1388 AND
	s.survey_id in (565, 645, 562)
```

Followed by this query to cause the `cache_samples_nonfunctional.attrs_json` to be recalculated
```
INSERT INTO work_queue (task, entity, record_id, priority, cost_estimate, created_on)
SELECT DISTINCT 'task_cache_builder_attrs_sample', 'sample', sample_id, 2, 60, now()
FROM sample_attribute_values
WHERE sample_attribute_id = 1660
	AND updated_by_id = 2
	AND date(updated_on) = '2022-11-29'
```

This fails to update 21 records in `cache_samples_nonfunctional` where the temperature attribute had been marked as deleted. They continue to hold a reference to `smpAttr:1388`. The following query overcomes this.
```
UPDATE cache_samples_nonfunctional snf
SET attrs_json = attrs_json::jsonb - '1388'
FROM sample_attribute_values sav
WHERE 
	snf.id = sav.sample_id AND
	sav.sample_attribute_id = 1660 AND
	sav.updated_by_id = 2 AND
	date(sav.updated_on) = '2022-11-29' AND
	sav.deleted = true
```

Finally, this query prompts ElasticSearch to update
```
UPDATE cache_samples_functional s
SET tracking = null
FROM sample_attribute_values sav
WHERE 
	s.id = sav.sample_id AND
	sav.sample_attribute_id = 1660 AND
	sav.updated_by_id = 2 AND
	date(sav.updated_on) = '2022-11-29'
```

**Comment by johnvanbreda** [comment] 2022-12-01 15:35
Any particular IDs @JimBacon? I've checked a few recent deletions from iRecord and they seem to have been removed correctly.

**Comment by JimBacon** [comment] 2022-12-01 15:39
E.g. Samples 8029261, 11868076, 11966510, 18588200

**Comment by JimBacon** [comment] 2022-12-01 15:41
@johnvanbreda Can you give me a quick pointer as to how the deletion works as the records are no longer be in the cache tables  so no longer have a tracking number. Maybe there is some documentation?

**Comment by JimBacon** [comment] 2022-12-07 18:07
To answer my own question, it looks like there are two LogStash configuration files, one for samples and one for occurrences, which remove records from the indices based upon the results of two reports, `library/samples/list_sample_deletions_all.xml` and `library/occurrences/list_occurrence_deletions_all.xml`

The variables table contains two settings, `rest-autofeed-BRCSMPDEL` and `rest-autofeed-BRC5DEL` for recording the timestamp up to which updates have been completed. 

It looks like we can trigger record deletions in ElasticSearch, where they have failed previously for some reason, by setting `updated_on = now()` for occurrences and samples that are marked as deleted in Postgres. I should test that it causes ElasticSearch no problem if it tries to delete a record that has already been removed.

**Comment by JimBacon** [comment] 2023-01-26 09:42
Closing this issue as complete but have opened https://github.com/Indicia-Team/warehouse/issues/471 regarding the removal of deleted samples from ElasticSearch.

**Closed by JimBacon** 2023-01-26 09:42 UTC
