### ISSUE TITLE
Problem with the default language of the Menu: it is in Croatian

### ISSUE THREAD

**Issue by CrisSevilleja** [BiologicalRecordsCentre/ABLE#167] opened 2019-11-28 17:04 UTC
@DavidRoy the eBMS menu and the title heads of every tab appear by default in Croatian. I translated the eBMS Menu to Croatian and it was applied as default language although English is still the default language in the translation tab... 
In languages with the complete Menu translated is not a problem but for others like Italian, the menu appear half in Italian and half in Croatian. I don't what I changed but it looks like I did it. 
Sorry for that I hope it is easy to change.

**Comment by DavidRoy** [comment] 2019-11-28 17:12
@Gary-van-Breda can you investigate as a priority please as I’m currently travelling. Thanks

**Comment by Gary-van-Breda** [comment] 2019-11-29 12:42
I don't think this is @CrisSevilleja 's fault. I note that Croatian come before English when listing the Languages in alphabetic order, and the those without Croatian default to English. Something weird is happening in Drupal itself - am investigating

**Comment by CrisSevilleja** [comment] 2019-11-29 14:04
@Gary-van-Breda good to hear that I didn't make it. I saw it is already fixed. Thanks!

**Comment by Gary-van-Breda** [comment] 2019-11-29 14:07
On https://butterfly-monitoring.net/admin/config/regional/language it states that the order of the languages on that page has no impact on the detection and selection of the translation to be used. This is misleading - it has no impact on the detection of which language translation it should use, but the order displayed is the order used to determine a fallback language if there is no translation in the requested language (see function getFallbackCandidates()).  
I have moved English to the top of the list. This means that English will be the default translation. The down side of this is that English is now at the top of the list displayed in the language selector: the list is no longer in alphabetical order.  
@DavidRoy Is this acceptable? If not I can write a hook for 'language_fallback_candidates' which can put English at the top of the list invisibly - probably an hour's work now that I know what's happening.  
  
Just to reiterate, this is caused by a "feature" of Drupal language management, and not anything @CrisSevilleja did.

**Comment by DavidRoy** [comment] 2019-11-29 14:41
Thanks Gary.  That's ok.  We can make the argument that English is the default language as all the content starts off in that language.

Closing the issue now

**Closed by DavidRoy** 2019-11-29 14:41 UTC
Labels: urgent, website: general
