### ISSUE TITLE
Issue: duplicated pictures when submitting moth trap survey from app

### ISSUE THREAD

**Issue by CrisSevilleja** [BiologicalRecordsCentre/ABLE#727] opened 2024-10-09 16:33 UTC
### Describe the issue

A user recording moth traps (user ID 289556) experienced duplicated pictures when uploading the moth trap survey from the app to the website. When reviewing the visit on the website, she found several pictures duplicated on the record and counted the number of individuals wrong due to this. She already deleted the duplicated pictures for the visits in August (2nd and 16th). Still, she tried again, and the visits of 11/09/2024 had duplicated pictures, increasing the number of individuals wrongly for some species. 
On the screenshots, she selected a whole bunch of pictures, 122 selected pictures from the gallery to add to the Automatic Identification of the app. 80 species were unknown (not identified by the app) and 46 pictures were identified by the app.
Counting all the individuals I get 244 individuals, almost all pictures duplicates. I checked the first species on the survey and all the first species have duplicated pictures and then the wrong number of individuals. 

The user confirmed that she didn't increase the number of individuals during the visit, she only used the automatic identification tool for the moth trap visit. 

One important thing, the place where she records doesn't have the best internet connection so I am wondering if that is affecting the automatic identification and producing this bug on the app. 

### Expected behaviour

Insert pictures into the automatic identification tool of the app and get the correct number of individuals without duplicating pictures. 

### To Reproduce

1. Go to the ButterflyCount app
2. Open a moth trap survey
3. Select the trap
4. Select the camera icon for using the automatic identification tool
5. get the list of identified species and unknown individuals by pictures uploaded

### App Version

1.26.5

### Device

Xiaomi 11 Lite, Android 14

### When did this happen

11/09/2024 it happened several times before, surveys in August

### Screenshots

![selected_record_fromLibrary](https://github.com/user-attachments/assets/88415db9-6153-49f9-9729-4d59ba827cb2)
![unknown_records](https://github.com/user-attachments/assets/6d5ea678-1021-4615-ba1c-ec3fe2560fee)
![identified_records](https://github.com/user-attachments/assets/d6e617c8-7f10-434a-94ed-f03be855bbf1)

**Comment by kazlauskis** [comment] 2024-10-21 06:34
I am unsure why this has happened and I can't reproduce this either, but I have added extra safeguards so it checks for duplicates in the app now. This will come out in the following app release v1.26.6. I am closing this issue for now, please reopen it if someone reports this again.

**Closed as completed by kazlauskis** 2024-10-21 06:34 UTC
Labels: app, moth
